//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuoYun.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarResource
    {
        public string ID { get; set; }
        public string UID { get; set; }
        public Nullable<System.DateTime> PDATE { get; set; }
        public string StartAreaID { get; set; }
        public string EndAreaID1 { get; set; }
        public string EndAreaID2 { get; set; }
        public string EndAreaID3 { get; set; }
        public string EndAreaID4 { get; set; }
        public string EndAreaID5 { get; set; }
        public Nullable<System.DateTime> FreeDate { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditMan { get; set; }
    }
}
