//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuoYun.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public string ID { get; set; }
        public string TCode { get; set; }
        public string Name { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public string Spare4 { get; set; }
        public string Spare5 { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditMan { get; set; }
    }
}
