//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuoYun.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GoodsResources
    {
        public string ID { get; set; }
        public string UID { get; set; }
        public Nullable<System.DateTime> PDATE { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Len { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Occupied { get; set; }
        public string GoodsTypeID { get; set; }
        public byte[] Img1 { get; set; }
        public byte[] Img2 { get; set; }
        public byte[] Img3 { get; set; }
        public byte[] Img4 { get; set; }
        public byte[] Img5 { get; set; }
        public byte[] Img6 { get; set; }
        public byte[] Img7 { get; set; }
        public byte[] Img8 { get; set; }
        public byte[] Img9 { get; set; }
        public string StartAreaID { get; set; }
        public string StartAddr { get; set; }
        public string EndAreaID { get; set; }
        public string EndAddr { get; set; }
        public Nullable<decimal> CarLenReq { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditMan { get; set; }
    }
}
